"""Recommendation model for AI-powered inventory predictions.

Stores ML predictions for what products to bring to market.
"""
from datetime import datetime
from typing import Optional
from decimal import Decimal

from sqlalchemy import String, Numeric, DateTime, Integer, Text, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID as PGUUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import TenantModel


class Recommendation(TenantModel):
    """
    Recommendation represents an AI prediction for market inventory.

    Generated by ML model based on:
    - Historical sales data
    - Weather forecast
    - Market events
    - Seasonal patterns
    """

    __tablename__ = "recommendations"

    # Target market date
    market_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Date of farmers market",
    )

    # Product being recommended
    product_id: Mapped[PGUUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey('products.id', ondelete='CASCADE'),
        nullable=False,
        comment="Product to bring",
    )

    # Venue (optional - if not specified, recommendation is date-only)
    venue_id: Mapped[Optional[PGUUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey('venues.id', ondelete='SET NULL'),
        nullable=True,
        index=True,
        comment="Venue/market location (optional)",
    )

    # Prediction
    recommended_quantity: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Recommended quantity to bring",
    )

    confidence_score: Mapped[Decimal] = mapped_column(
        Numeric(5, 4),
        nullable=False,
        comment="Model confidence (0.0 to 1.0)",
    )

    # Expected metrics
    predicted_sales: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Predicted units to sell",
    )

    predicted_revenue: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 2),
        nullable=True,
        comment="Predicted revenue in USD",
    )

    # Context features used for prediction (stored as JSON)
    weather_features: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Weather forecast data used",
    )

    event_features: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Event data used",
    )

    historical_features: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Historical patterns used",
    )

    # Model metadata
    model_version: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="ML model version used",
    )

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default='NOW()',
        comment="When recommendation was generated",
    )

    # User feedback
    user_accepted: Mapped[Optional[bool]] = mapped_column(
        nullable=True,
        comment="Whether vendor accepted recommendation",
    )

    actual_quantity_brought: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Actual quantity vendor brought",
    )

    # Relationship to feedback
    feedback: Mapped[Optional["RecommendationFeedback"]] = relationship(
        "RecommendationFeedback",
        back_populates="recommendation",
        uselist=False,
        cascade="all, delete-orphan",
    )

    # Additional indexes for queries
    __table_args__ = (
        Index('ix_recommendations_vendor_market_date', 'vendor_id', 'market_date'),
        Index('ix_recommendations_product_date', 'product_id', 'market_date'),
        Index('ix_recommendations_vendor_generated', 'vendor_id', 'generated_at'),
        Index('ix_recommendations_venue_date', 'venue_id', 'market_date'),
    )

    def __repr__(self) -> str:
        """String representation."""
        return (
            f"<Recommendation(id={self.id}, vendor_id={self.vendor_id}, "
            f"venue_id={self.venue_id}, market_date={self.market_date}, "
            f"product_id={self.product_id}, quantity={self.recommended_quantity})>"
        )
